[package]
name = "word-embeddings-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
candle-core = { version = "0.3.0" }
env_logger = "0.10.0"
log = "0.4.20"
rand = "0.8.5"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
